### PR TITLE
PLANET-3201 - Using CSS columns rather than flexbox for submenu layout

### PR DESCRIPTION
**Pull request by tomisaacmarshall**
Hello

Gabor asked us to address the issue whereby submenu items are ordered left-to-right first, rather then top-to-bottom, when they appear in columns, e.g. here: https://www.greenpeace.org/international/explore/about/worldwide/

This PR uses CSS columns instead of flex to ensure they are ordered top-to-bottom first. 

(As was suggested by Tam in his original PR here: https://github.com/greenpeace/planet4-plugin-blocks/pull/440)

### CODE REVIEW

**Comment by koyan** [comment]
Note: This should complete the work at [PLANET-3072](https://jira.greenpeace.org/browse/PLANET-3072?focusedCommentId=96622)

**Comment by comzeradd** [comment]
Please rebase and regenerate the styles.

**Comment by tomisaacmarshall** [comment]
@comzeradd Thanks for sorting!

This branch has been superseded by this and could be deleted btw https://github.com/greenpeace/planet4-plugin-blocks/tree/submenu-design-update

**Comment by koyan** [comment]
Done,  branch (And other  stale ones) deleted.

**Pull request merged**
