### PR TITLE
PLANET-3721: Apply vertical spacing to Oil Campaign

### PR DESCRIPTION
**Pull request by pablocubico**
Ref: https://jira.greenpeace.org/browse/PLANET-3721

### CODE REVIEW

**Comment by comzeradd** [comment]
Let's hold merging this till tomorrow, in case UAT get delayed, so we don't delay the release. We can include it in the next one.

**Comment by comzeradd** [comment]
@pablocubico should we merge this?

**Comment by pablocubico** [comment]
> @pablocubico should we merge this?

@comzeradd I'll push for feedback, I uploaded it to my test environment in order to merge after design review

**Comment by pablocubico** [comment]
@comzeradd Merging as this was UAT'd on JIRA.

**Pull request merged**
